### PR TITLE
fixes for 0.7

### LINKED ISSUE #661: The kernel appears to have died. It will restart automatically Julia V0.7
Kernel dies when running the nightly build in Julia v0.7. I am using ``` "ZMQ"=> v"0.6.0+"``` and ```"Conda"=> v"0.7.1+"```, ```MbedTLS=> v"0.5.8+```. 

Running ```Pkg.build("IJulia")``` is successful and besides the deprecations, it doesn't give me any error. 

The output of the Jupyter window right before the error is 

```Julia

┌ Warning: The function `cfunction` is now written as a macro `@cfunction`.
│   caller = start_heartbeat at heartbeat.jl:18 [inlined]
└ @ Core heartbeat.jl:18
[I 17:35:19.910 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel cc809c67-d194-447d-9d74-a5a05f21dc83 restarted


```

### PR DESCRIPTION
**Pull request by fredrikekre**
This is  #623 + #667 + two additional fixes.  Closes #661, #654, #637.

This PR works locally on both 0.7 and 0.6 for me, would be great to get IJulia to work properly on 0.7!

### CODE REVIEW

File: src/inline.jl [hunk 1]
```diff
@@ -1,6 +1,9 @@
 import Base: display, redisplay
 
-immutable InlineDisplay <: Display end
+@static if !isdefined(Base, :AbstractDisplay) # remove when Compat.jl#482 is merged and tagged
```
Comment (stevengj) [inline src/inline.jl]: Shouldn't this be:
```jl
if !isdefined(Base, :AbstractDisplay) && !isdefined(Compat, :AbstractDisplay)
  ...
```
(No need for `@static` in global scope unless the expressions have `ccall` or macros...)

**Comment by stevengj** [comment]
Great, thanks for working on this!  Sorry I haven't had time to bang on it.

Do things like `println` now work in both 0.6 and 0.7?

File: src/inline.jl (hunk 1 above)
Comment (stevengj) [reply src/inline.jl]: Actually, this if statement can be deleted completely as the `AbstractDisplay` definition was tagged in Compat v0.52.0

**Comment by fredrikekre** [comment]
Pushed one more deprecation fix and updated to use `Compat.AbstractDisplay` directly.

> Do things like println now work in both 0.6 and 0.7?

Yes! :tada:

File: src/stdio.jl [hunk 2]
```diff
@@ -27,36 +27,51 @@ Base.setup_stdio(io::IJuliaStdio, readable::Bool) = Base.setup_stdio(io.io.io, r
...
+    sq = QuoteNode(Symbol(s))
     @eval function Base.$f(io::IJuliaStdio)
         io[:jupyter_stream] != $s && throw(ArgumentError(string("expecting ", $s, " stream")))
-        eval(Base, Expr(:(=), $S, io))
+        if isdefined(Base, :stdout)
+            # On Julia 0.7, we need to override the global logger as well
+            logger = Base.CoreLogging._global_logstate.logger
+
+            # Override logging if it's pointing at the default stderr
+            if logger.stream == Base.stderr
```
Comment (fredrikekre) [inline src/stdio.jl]: Actually, there is something bugged here; this is only true on the first call, don't we need to reset it somewhere @staticfloat ? On this branch; with a `@show logger.stream == Base.stderr` inserted:
```
julia> using IJulia

julia> mktemp() do path, io
           redirect_stderr(IJulia.IJuliaStdio(io, "stderr")) do
               @warn("warn")
           end
           flush(io)
           seek(io, 0)
           @show read(io, String)
       end
logger.stream == Base.stderr = true
read(io, String) = "\e[33m\e[1m┌ \e[22m\e[39m\e[33m\e[1mWarning: \e[22m\e[39mwarn\n\e[33m\e[1m└ \e[22m\e[39m\e[90m@ Main REPL[2]:3\e[39m\n"
"\e[33m\e[1m┌ \e[22m\e[39m\e[33m\e[1mWarning: \e[22m\e[39mwarn\n\e[33m\e[1m└ \e[22m\e[39m\e[90m@ Main REPL[2]:3\e[39m\n"

julia> mktemp() do path, io
           redirect_stderr(IJulia.IJuliaStdio(io, "stderr")) do
               @warn("warn")
           end
           flush(io)
           seek(io, 0)
           @show read(io, String)
       end
logger.stream == Base.stderr = false
read(io, String) = ""
```

Comment (fredrikekre) [reply src/stdio.jl]: Perhaps it does not matter; this seems to be called only once per session anyways and it works in a notebook
warning

Comment (fredrikekre) [reply src/stdio.jl]: Would it not be simpler to just replace the global logger instead of checking the internal state?

**Comment by fredrikekre** [comment]
I updated the logging redirect, now things seem to work:
working

File: src/handlers.jl [hunk 3]
```diff
@@ -138,7 +138,7 @@ function complete_request(socket, msg)
 
     codestart = find_parsestart(code, cursorpos)
     comps, positions = Base.REPLCompletions.completions(code[codestart:end], cursorpos-codestart+1)
```
Comment (stevengj) [inline src/handlers.jl]: Probably need:
```jl
if VERSION < v"0.7.0-DEV.3500" # julia#25544
    import Base: REPLCompletions
else
    import REPL: REPLCompletions
end
```
above so that we can just call this as `REPLCompletions.completions` with no deprecation warning.

Comment (fredrikekre) [reply src/handlers.jl]: Thanks, there was a similar `if VERSION` check at the top so I added the imports there.

**Comment by fredrikekre** [comment]
While trying the tab-completion for deprecations I got this
```
BoundsError: attempt to access 0-element Array{Int64,1} at index [0]
```
Seems to be a bug here https://github.com/JuliaLang/IJulia.jl/blob/90b0165cf0902f9ca678f968d63e8834119ccc63/src/handlers.jl#L144-L145 where we try to extract the last element although we just made sure it's empty.

**Comment by stevengj** [comment]
Maybe should be `cursor_start = cursor_end = cursor_chr`

File: src/handlers.jl [hunk 4]
```diff
@@ -134,8 +140,8 @@ function complete_request(socket, msg)
     end
 
     codestart = find_parsestart(code, cursorpos)
-    comps, positions = Base.REPLCompletions.completions(code[codestart:end], cursorpos-codestart+1)
-    positions += codestart-1
+    comps, positions = REPLCompletions.completions(code[codestart:end], cursorpos-codestart+1)
+    positions = positions .+ codestart-1
```
Comment (fredrikekre) [inline src/handlers.jl]: Nevermind, it is this fix that is missing a `.` on the `-` and the range turned into an array. Of course last works for an empty range.

File: src/handlers.jl [hunk 5]
```diff
@@ -134,8 +140,8 @@ function complete_request(socket, msg)
     end
 
     codestart = find_parsestart(code, cursorpos)
-    comps, positions = Base.REPLCompletions.completions(code[codestart:end], cursorpos-codestart+1)
-    positions += codestart-1
+    comps, positions = REPLCompletions.completions(code[codestart:end], cursorpos-codestart+1)
+    positions = positions .+ codestart .- 1
```
Comment (fredrikekre) [inline src/handlers.jl]: Hmm, still not correct; this returns a `Vector` on Julia 0.6.

**Comment by stevengj** [comment]
LGTM, ready to merge?

File: src/IJulia.jl [hunk 6]
```diff
@@ -198,7 +202,7 @@ function clear_history(indices)
 end
 
 # since a range could be huge, intersect it with 1:n first
-clear_history{T<:Integer}(r::AbstractRange{T}) =
+clear_history(r::AbstractRange{T}) where {T<:Integer} =
```
Comment (stevengj) [inline src/IJulia.jl]: Can just be `clear_history(r::AbstractRange{<:Integer})` since we don't use `T`.

File: src/execute_request.jl [hunk 7]
```diff
@@ -58,30 +56,50 @@ const displayqueue = Any[]
 
 # remove x from the display queue
 function undisplay(x)
-    i = findfirst(equalto(x), displayqueue)
-    if i > 0
+    i = findfirst(isequal(x), displayqueue)
```
Comment (stevengj) [inline src/execute_request.jl]: Shouldn't this be `Compat.findfirst` to get the version that returns `nothing` on 0.6?

File: src/execute_request.jl [hunk 8]
```diff
@@ -58,30 +56,50 @@ const displayqueue = Any[]
...
+    import Base.REPL: ip_matches_func
+else
+    import Base: ip_matches_func
+end
+
 function show_bt(io::IO, top_func::Symbol, t, set)
     # follow PR #17570 code in removing top_func from backtrace
-    eval_ind = findlast(addr->Base.REPL.ip_matches_func(addr, top_func), t)
-    eval_ind != 0 && (t = t[1:eval_ind-1])
+    eval_ind = findlast(addr->ip_matches_func(addr, top_func), t)
```
Comment (stevengj) [inline src/execute_request.jl]: Similar to above, use `Compat.findlast` and then you can skip the `eval_ind != 0` check.

**Comment by stevengj** [comment]
I'm just going to merge this as-is so that people can use IJulia with 0.7, and then add more fixes in another PR.

**Comment by fredrikekre** [comment]
Thanks! I have to admit that I did not review the changes from  #623 myself.
